version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "14:15"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "14:15"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"

  - package-ecosystem: "hex"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "14:15"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
